# Site settings
title: Web development 
header-img: img/home-bg.png
email: waasif.khaan@gmail.com
copyright_name: waasifkhaan
description: > # this means to ignore newlines until "baseurl:"
  Hash Manipulation in Ruby
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  waasifkhaan
learn_profile: waasifkhaan
email_username: waasif.khaan@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
